apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-app
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: devops_learning
  DB_USER: postgres
  DB_PASSWORD: "<YOUR_PASSWORD>"
